version: '2.1'
services:
  api:
    image: twk/json-server:latest
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
  python-tests:
    image: twk/python-tests:latest
    environment:
      - BASE_URI=http://api:3000
    volumes:
      - ./reports:/tests/reports
    command: bash -c "./wait-for.sh api:3000 && pytest -s test_1.py --html=reports/report.html --self-contained-html"
